clonegram/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth.views import logout_then_login

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('fotos.urls')),
    path('usuario/', include('usuarios.urls')),
    path('logout', logout_then_login, name='logout')
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

fotos/urls.py
from fotos import views
from django.urls import path
from django.contrib.auth.decorators import login_required

app_name = 'fotos'

urlpatterns = [
    path('', login_required(views.home), name="home"),
    path('postnuevo/', login_required(views.post_form), name="post_nuevo"),
    path('postear/', login_required(views.subir_foto), name="postear"),
    path('<int:id>/detalles/', login_required(views.pub_detalles), name="pub_detalles"),
    path('<int:id>/likear/', login_required(views.likear), name='likear'),
    path('<int:id>/guardar/', login_required(views.guardar_post), name='guardar'),
    path('<int:id>/comentar/', login_required(views.comentar), name='comentarios'),
    path('<int:id>/likes/', login_required(views.get_likes), name='like'),
    path('guardados/', login_required(views.get_saved), name='saved'),
    path('<int:id>/comentarios/', login_required(views.post_comments), name='comentarios_re'),
    path('buscar/', login_required(views.busqueda), name='buscar'),
    path('notificaciones/', login_required(views.notificaciones), name='ntc'),
]

usuarios/urls.py
from usuarios import views
from django.urls import path
from django.contrib.auth.decorators import login_required

app_name = 'usuario'

urlpatterns = [
    path('loginhome/', views.login_home, name='login_home'),
    path('registrarsehome/', views.registrarse_home, name='registrarse_home'),
    path('registrarse/', views.registrarse, name='registrarse'),
    path('login/', views.login_user, name='login'),
    path('home/', login_required(views.user_home), name='user_home'),
    path('<int:id>/editar/', login_required(views.edit_user), name='editar'),
    path('<int:id>/perfil/', login_required(views.user_profile), name='user_profile'),
    path('resultados/', login_required(views.resultados), name='resultados'),
    path('<int:id>/follow/', login_required(views.follow_user), name='follow'),
]

usuarios/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.conf import settings

class Usuario(AbstractUser):
    foto_perfil = models.ImageField(blank=True, null=True, upload_to='covers/%Y/%m/%D/')
    followers = models.ManyToManyField(settings.AUTH_USER_MODEL, blank=True, symmetrical=False, related_name='userfollowers')
    following = models.ManyToManyField(settings.AUTH_USER_MODEL, blank=True, symmetrical=False, related_name='userfollowing')
    bio = models.CharField(max_length=400, blank=True)

    @property
    def count_followers(self):
        return self.followers.count()
    
    @property
    def count_following(self):
        return self.following.count()

usuarios/forms.py
from django import forms
from .models import Usuario


class UserForm(forms.ModelForm):
    class Meta:
        model = Usuario
        fields = [
            'username',
            'first_name',
            'last_name',
            'foto_perfil',
            'bio'
        ]
        widgets = {
            'username': forms.TextInput(attrs={'placeholder': 'Nombre de usuario'}),
            'first_name': forms.TextInput(attrs={'placeholder': 'Nombre'}),
            'last_name': forms.TextInput(attrs={'placeholder': 'Apellido'}),
            'bio': forms.TextInput(attrs={'placeholder': 'Biografia'}),
            'foto_perfil': forms.FileInput(),
        }

usuarios/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, JsonResponse
from django.contrib.auth import login, authenticate
from django.contrib.auth.hashers import check_password
from .models import Usuario
from fotos.models import Notificaciones
from fotos.models import Post
from .forms import UserForm
import re
from django.db.models import Q
from django.utils import timezone

def login_home(request):
    return render(request, 'usuarios/login.html')

def registrarse_home(request):
    return render(request, 'usuarios/registrarse.html')

def user_home(request):
    fotos = Post.objects.filter(usuario_id=request.user.id)
    contexto = {'fotos': fotos}
    return render(request, 'usuarios/user_home.html', contexto)

def user_profile(request, id):
    following = False
    user = Usuario.objects.get(id=id)
    fotos = Post.objects.filter(usuario_id=user.id)
    if user.followers.filter(id=request.user.id).exists():
        following = True
    contexto = {'usuario': user, 'fotos': fotos, 'following': following}
    return render(request, 'usuarios/user_page.html', contexto)

def registrarse(request):
    salida = {}
    if request.method == 'POST' and request.is_ajax():
        username_ = request.POST.get('username')
        nombre_ = request.POST.get('nombre')
        apellido_ = request.POST.get('apellido')
        email_ = request.POST.get('email')
        pass_ = request.POST.get('password')
        pass_confir = request.POST.get('password2')

        if username_ and nombre_ and apellido_ and email_ and pass_ and pass_confir:
            ex_regular = r"^[A-Za-z0-9\.\+_-]+@[A-Za-z0-9\._-]+\.[a-zA-Z]*$"
            if re.match(ex_regular, email_):
                if len(pass_) > 6:
                    if pass_ == pass_confir:
                        if not(Usuario.objects.filter(username=username_).exists()):
                            if not(Usuario.objects.filter(email=email_).exists()):
                                user = Usuario.objects.create(
                                    username=username_,
                                    first_name=nombre_,
                                    last_name=apellido_,
                                    email=email_,
                                    password=pass_
                                )
                                user.set_password(request.POST.get('password'))
                                user.save()
                                user = authenticate(username=username_, password=pass_)
                                login(request, user)
                                salida = {'success': True, 'msj': 'Registrado'}
                            else:
                                salida = {'error': True, 'msj': 'Ese email ya esta registrado'}
                        else:
                            salida = {'error': True, 'msj': 'Ese nombre de usuario ya esta registrado'}
                    else:
                        salida = {'error': True, 'msj': 'Las contraseñas no coinciden'}
                else:
                    salida = {'error': True, 'msj': 'Por favor ingresa una contraseña mas larga'}
            else:
                salida = {'error': True, 'msj': 'Por favor ingresa un email valido'}
        else:
            salida = {'error': True, 'msj': 'Por favor llena todos los campos'}
    return HttpResponse(JsonResponse(salida))

def login_user(request):
    salida = {}
    if request.method == 'POST' and request.is_ajax():
        username_ = request.POST.get('username')
        password_ = request.POST.get('password')

        if username_ and password_:
            if Usuario.objects.filter(username=username_).exists():
                get_user = Usuario.objects.get(username=username_)
                get_pass = get_user.password
                if check_password(password_, get_pass):
                    user = authenticate(username=username_, password=password_)
                    if user is not None:
                        login(request, user)
                        salida = {'success': True, 'msj': 'Login Correcto'}
                else:
                    salida = {'error': True, 'msj': 'Contraseña incorrecta.'}
            else:
                salida = {'error': True, 'msj': 'Ese usuario no esta registrado, intenta nuevamente'}
        else:
            salida = {'error': True, 'msj': 'Por favor llena los todos los campos'}
    return HttpResponse(JsonResponse(salida))

def edit_user(request, id):
    user = Usuario.objects.get(id=request.user.id)
    if request.method == 'GET':
        form = UserForm(instance=user)
    else:
        form = UserForm(data=request.POST, files=request.FILES, instance=user)
        if form.is_valid():
            form.save()
            return redirect('usuario:user_home')
    return render(request, 'usuarios/editar_perfil.html', {'form': form})


def resultados(request):
    salida = {}
    user = request.GET.get('usuario')
    if len(user) > 0:
        if request.is_ajax():
            usuarios = Usuario.objects.filter(Q(username__icontains=user)).exclude(username=request.user.username)
            results = []
            for objeto in usuarios:
                basic = {}
                basic['id'] = objeto.id
                basic['username'] = objeto.username
                results.append(basic)
            salida = {'success': True, 'objetos': results}
    return HttpResponse(JsonResponse(salida))

def follow_user(request, id):
    salida = {}
    usuario = Usuario.objects.get(id=id)
    current_user = request.user
    date = timezone.now()
    if usuario.followers.filter(id=current_user.id).exists():
        salida = {'unfollowed': True}
        usuario.followers.remove(current_user)
        current_user.following.remove(usuario)
    else:
        usuario.followers.add(current_user)
        current_user.following.add(usuario)
        texto_ = 'te ha seguido'
        ntc = Notificaciones.objects.create(
            f_user=current_user,
            fecha=date,
            s_user=usuario,
            texto=texto_
        )
        ntc.save()
        salida = {'followed': True}
    return HttpResponse(JsonResponse(salida))

templates/usuarios/editar_perfil.html
{% extends 'base.html' %}
{% block header %}
<div class="header">
    <a class="titulo" href="{% url 'fotos:home' %}">Clonegram</a>
</div>
{% endblock %}
{% block content %}
<div class="editform">
    <form method="POST" class="custom-form" action="{% url 'usuario:editar' request.user.id %}" enctype="multipart/form-data" novalidate="">
        {% csrf_token %}
        <h3>Actualizar informacion</h3>
        <div class="form-group text-center pt-2">
            {{ form.foto_perfil }}
        </div>
        <div class="form-group text-center">
            {{ form.username }}
        </div>
        <div class="form-group text-center">
            {{ form.first_name }}
        </div>
        <div class="form-group text-center">
            {{ form.last_name }}
        </div>
        <div class="form-group text-center">
            {{ form.bio }}
        </div>
        <div class="form-group text-center">
            <button type="submit" class="btn-full" id="submit_edit">Guardar</button>
        </div>
    </form>
</div>
{% endblock %}

templates/usuarios/login.html
{% extends 'base.html' %}
{% block header %}
{% endblock %}
{% block content %}
<div class="contenedor">
    <div class="presentacion">
        <i class="fas fa-camera"></i>
        <h1>CloneGram</h1>
    </div>
    <div class="presentacion_re">
        <h1>Clonegram</h1>
    </div>
    <div class="form">
        <div class="pad" style="padding-top: 100px;"></div>
        <h3>Loguearse</h3>
        <form class="custom-form" id="login_form">
            {% csrf_token %}
            <div class="form-group text-center pt-2">
                <input type="text" placeholder="Nombre de usuario" name="username">
            </div>
            <div class="form-group text-center">
                <input type="password" placeholder="Contraseña" name="password">
            </div>
            <div class="form-group text-center">
                <button type="submit" class="btn-full" id="submit_login">Ingresar</button>
                <div class="errores"></div>
            </div>
        </form>
        <div class="cuenta">
            <a href="{% url 'usuario:registrarse_home' %}">No tienes cuenta? Haz click aqui</a>
        </div>
    </div>
</div>
{% endblock %}
{% block footer %}
{% endblock %}

templates/usuarios/registrarse.html
{% extends 'base.html' %}
{% block header %}
{% endblock %}
{% block content %}
<div class="contenedor">
    <div class="presentacion">
        <i class="fas fa-camera"></i>
        <h1>CloneGram</h1>
    </div>
    <div class="form">
        <h3>Registrarse</h3>
        <form class="custom-form" id="register_form">
            {% csrf_token %}
            <div class="form-group text-center pt-2">
                <input type="text" placeholder="Nombre de usuario" name="username">
            </div>
            <div class="form-group text-center">
                <input type="text" placeholder="Nombre" name="nombre">
            </div>
            <div class="form-group text-center">
                <input type="text" placeholder="Apellido" name="apellido">
            </div>
            <div class="form-group text-center">
                <input type="text" placeholder="Email" name="email">
            </div>
            <div class="form-group text-center">
                <input type="password" placeholder="Contraseña" name="password">
            </div>
            <div class="form-group text-center">
                <input type="password" placeholder="Confirmar contraseña" name="password2">
            </div>
            <div class="form-group text-center">
                <button class="btn-full" id="submit_register">Ingresar</button>
                <div class="errores"></div>
            </div>
        </form>
        <div class="cuenta">
            <a href="{% url 'usuario:login_home' %}">Ya tienes cuenta? Haz click aqui</a>
        </div>
    </div>
</div>
{% endblock %}
{% block footer %}
{% endblock %}

templates/usuarios/user_home.html
{% extends 'base.html' %}

{% block content %}

<div class="header2">
    {% if not request.user.foto_perfil %}
        <div class="circle"><i class="fas fa-user"></i></div>
    {% else %}
        <img class="circle2" src={% if request.user.foto_perfil %}'{{ request.user.foto_perfil.url }}'{% endif %} alt="">
    {% endif %}
    <h1>{{request.user.username}}</h1>
    <h4>{{ request.user.first_name }} {{ request.user.last_name }}</h4>
    {% if request.user.bio %}
        <p>{{ request.user.bio }}</p>
    {% endif %}
    <div class="follows">
        <button data-toggle="modal" data-target="#modalfollowing" class="following">{{ request.user.count_following }} Seguidos</button>
        <button data-toggle="modal" data-target="#modalfollowers" class="followers">{{ request.user.count_followers }} Seguidores</button>
    </div>
</div>
<div class="publicaciones">
    <h2>Publicaciones</h2>
    <div class="subir_posteo">
        <a href="{% url 'fotos:post_nuevo' %}" class="btn-camera" title="Subir foto"><i class="fas fa-camera"></i></a>
    </div>
    {% if fotos %}
        {% for foto in fotos %}
            <div class="listado">
                <a href="{% url 'fotos:pub_detalles' foto.id %}">
                    <img src={% if foto.imagen %}'{{ foto.imagen.url }}'{% endif %} alt="">
                </a>
            </div>
        {% endfor %}
    {% else %}
        <h1>No hay publicaciones por el momento</h1>
    {% endif %}
</div>
<div class="modal fade" id="modalfollowers" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content" id="modal">
            <div class="modal-header text-center">
                <h4 class="modal-title w-100" id="modaltit">Seguidores</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body mx-3" id="control">
                {% for follower in request.user.followers.all %}
                    {% if follower.foto_perfil %}
                        <div class="md-form mb-2 d-flex justify-content-center">
                            <a class="link_user" href="{% url 'usuario:user_profile' follower.id %}">
                                <img class="circle3" src={% if follower.foto_perfil %}'{{ follower.foto_perfil.url }}'{% endif %} alt="">
                                {{ follower.username }}
                            </a>
                        </div>
                    {% else %}
                        <div class="md-form mb-2 d-flex justify-content-center">
                            <a class="link_user" href="{% url 'usuario:user_profile' follower.id %}">
                                <i class="fas fa-user"></i>
                                {{ follower.username }}
                            </a>
                        </div>
                    {% endif %}
                {% endfor %}
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="modalfollowing" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content" id="modal">
            <div class="modal-header text-center">
                <h4 class="modal-title w-100" id="modaltit">Siguiendo</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body mx-3" id="control">
                {% for following in request.user.following.all %}
                    {% if following.foto_perfil %}
                        <div class="md-form mb-2 d-flex justify-content-center">
                            <a class="link_user" href="{% url 'usuario:user_profile' following.id %}">
                                <img class="circle3" src={% if following.foto_perfil %}'{{ following.foto_perfil.url }}'{% endif %} alt="">
                                {{ following.username }}
                            </a>
                        </div>
                    {% else %}
                        <div class="md-form mb-2 d-flex justify-content-center">
                            <a class="link_user" href="{% url 'usuario:user_profile' following.id %}">
                                <i class="fas fa-user"></i>
                                {{ following.username }}
                            </a>
                        </div>
                    {% endif %}
                {% endfor %}
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/usuarios/user_page.html
{% extends 'base.html' %}
{% block content %}
<div class="header2">
    {% if not usuario.foto_perfil %}
        <div class="circle"><i class="fas fa-user"></i></div>
    {% else %}
        <img class="circle2" src={% if usuario.foto_perfil %}'{{ usuario.foto_perfil.url }}'{% endif %} alt="">
    {% endif %}
    <h1>{{ usuario.username }}</h1>
    <div class="follow">
        <form id="follow_form">
            {% csrf_token %}
            {% if following %}
                <button value="{{ usuario.id }}" type="submit" id="unfollow" class="btnfollow"><i class="fas fa-user-check"></i></button>
                <button style="display: none;" value="{{ usuario.id }}" type="submit" id="follow" class="btnfollow">Seguir</button>
            {% else %}
                <button value="{{ usuario.id }}" type="submit" id="follow" class="btnfollow">Seguir</button>
                <button style="display: none;" value="{{ usuario.id }}" type="submit" id="unfollow" class="btnfollow"><i class="fas fa-user-check"></i></button>
            {% endif %}
        </form>
    </div>
    <h4>{{ usuario.first_name }} {{ usuario.last_name }}</h4>
    {% if usuario.bio %}
        <p>{{ usuario.bio }}</p>
    {% endif %}
    <div class="follows">
        <button data-toggle="modal" data-target="#modalfollowing" class="following">{{ usuario.count_following }} Seguidos</button>
        <button data-toggle="modal" data-target="#modalfollowers" class="followers">{{ usuario.count_followers }} Seguidores</button>
    </div>
</div>
<div class="publicaciones">
    <h2>Publicaciones</h2>
    {% if fotos %}
        {% for foto in fotos %}
            <div class="listado">
                <a href="{% url 'fotos:pub_detalles' foto.id %}">
                    <img src={% if foto.imagen %}'{{ foto.imagen.url }}'{% endif %} alt="">
                </a>
            </div>
        {% endfor %}
    {% else %}
        <h1>No hay publicaciones por el momento</h1>
    {% endif %}
</div>
<div class="modal fade" id="modalfollowers" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content" id="modal">
            <div class="modal-header text-center">
                <h4 class="modal-title w-100" id="modaltit">Seguidores</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body mx-3" id="control">
                {% for follower in usuario.followers.all %}
                    {% if follower == request.user %}
                        {% if follower.foto_perfil %}
                            <div class="md-form mb-2 d-flex justify-content-center">
                                <a class="link_user" href="{% url 'usuario:user_home' %}">
                                    <img class="circle3" src={% if follower.foto_perfil %}'{{ follower.foto_perfil.url }}'{% endif %} alt="">
                                    {{ follower.username }}
                                </a>
                            </div>
                        {% else %}
                            <div class="md-form mb-2 d-flex justify-content-center">
                                <a class="link_user" href="{% url 'usuario:user_home' %}">
                                    <i class="fas fa-user"></i>
                                    {{ follower.username }}
                                </a>
                            </div>
                        {% endif %}
                    {% else %}
                        {% if follower.foto_perfil %}
                            <div class="md-form mb-2 d-flex justify-content-center">
                                <a class="link_user" href="{% url 'usuario:user_profile' follower.id %}">
                                    <img class="circle3" src={% if follower.foto_perfil %}'{{ follower.foto_perfil.url }}'{% endif %} alt="">
                                    {{ follower.username }}
                                </a>
                            </div>
                        {% else %}
                            <div class="md-form mb-2 d-flex justify-content-center">
                                <a class="link_user" href="{% url 'usuario:user_profile' follower.id %}">
                                    <i class="fas fa-user"></i>
                                    {{ follower.username }}
                                </a>
                            </div>
                        {% endif %}
                    {% endif %}
                {% endfor %}
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="modalfollowing" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content" id="modal">
            <div class="modal-header text-center">
                <h4 class="modal-title w-100" id="modaltit">Siguiendo</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body mx-3" id="control">
                {% for follower in usuario.following.all %}
                    {% if follower == request.user %}
                        {% if follower.foto_perfil %}
                            <div class="md-form mb-2 d-flex justify-content-center">
                                <a class="link_user" href="{% url 'usuario:user_home' %}">
                                    <img class="circle3" src={% if follower.foto_perfil %}'{{ follower.foto_perfil.url }}'{% endif %} alt="">
                                    {{ follower.username }}
                                </a>
                            </div>
                        {% else %}
                            <div class="md-form mb-2 d-flex justify-content-center">
                                <a class="link_user" href="{% url 'usuario:user_home' %}">
                                    <i class="fas fa-user"></i>
                                    {{ follower.username }}
                                </a>
                            </div>
                        {% endif %}
                    {% else %}
                        {% if follower.foto_perfil %}
                            <div class="md-form mb-2 d-flex justify-content-center">
                                <a class="link_user" href="{% url 'usuario:user_profile' follower.id %}">
                                    <img class="circle3" src={% if follower.foto_perfil %}'{{ follower.foto_perfil.url }}'{% endif %} alt="">
                                    {{ follower.username }}
                                </a>
                            </div>
                        {% else %}
                            <div class="md-form mb-2 d-flex justify-content-center">
                                <a class="link_user" href="{% url 'usuario:user_profile' follower.id %}">
                                    <i class="fas fa-user"></i>
                                    {{ follower.username }}
                                </a>
                            </div>
                        {% endif %}
                    {% endif %}
                {% endfor %}
            </div>
        </div>
    </div>
</div>
{% endblock %}