clonegram/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth.views import logout_then_login

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('fotos.urls')),
    path('usuario/', include('usuarios.urls')),
    path('logout', logout_then_login, name='logout')
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

fotos/urls.py
from fotos import views
from django.urls import path
from django.contrib.auth.decorators import login_required

app_name = 'fotos'

urlpatterns = [
    path('', login_required(views.home), name="home"),
    path('postnuevo/', login_required(views.post_form), name="post_nuevo"),
    path('postear/', login_required(views.subir_foto), name="postear"),
    path('<int:id>/detalles/', login_required(views.pub_detalles), name="pub_detalles"),
    path('<int:id>/likear/', login_required(views.likear), name='likear'),
    path('<int:id>/guardar/', login_required(views.guardar_post), name='guardar'),
    path('<int:id>/comentar/', login_required(views.comentar), name='comentarios'),
    path('<int:id>/likes/', login_required(views.get_likes), name='like'),
    path('guardados/', login_required(views.get_saved), name='saved'),
    path('<int:id>/comentarios/', login_required(views.post_comments), name='comentarios_re'),
    path('buscar/', login_required(views.busqueda), name='buscar'),
    path('notificaciones/', login_required(views.notificaciones), name='ntc'),
]

usuarios/urls.py
from usuarios import views
from django.urls import path
from django.contrib.auth.decorators import login_required

app_name = 'usuario'

urlpatterns = [
    path('loginhome/', views.login_home, name='login_home'),
    path('registrarsehome/', views.registrarse_home, name='registrarse_home'),
    path('registrarse/', views.registrarse, name='registrarse'),
    path('login/', views.login_user, name='login'),
    path('home/', login_required(views.user_home), name='user_home'),
    path('<int:id>/editar/', login_required(views.edit_user), name='editar'),
    path('<int:id>/perfil/', login_required(views.user_profile), name='user_profile'),
    path('resultados/', login_required(views.resultados), name='resultados'),
    path('<int:id>/follow/', login_required(views.follow_user), name='follow'),
]

fotos/models.py
from django.db import models
from django.conf import settings

class Post(models.Model):
    imagen = models.ImageField(blank=True, null=True, upload_to='covers/%Y/%m/%D/')
    fecha = models.DateField(auto_now_add=True)
    pie = models.CharField(max_length=500)
    usuario = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    guardar = models.ManyToManyField(settings.AUTH_USER_MODEL, blank=True, related_name='guardar')

    def __str__(self):
        return self.pie

    @property
    def num_likes(self):
        padre = self.likes.count()
        return padre
    
    @property
    def comments(self):
        return self.comentarios.all()


class Like(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='likes')
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name='user_likes'
    )
    fecha = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.user

class ComentarioPost(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comentarios')
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    texto = models.CharField(max_length=200)
    fecha = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.texto

class Notificaciones(models.Model):
    f_user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name='current_user',
        blank=True, null=True
    )
    texto = models.CharField(max_length=50)
    s_user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        blank=True, null=True
    )
    fecha = models.DateField(auto_now_add=True)
    post = models.ForeignKey(Post, on_delete=models.CASCADE, blank=True, null=True)

fotos/views.py
from django.utils import timezone
from django.shortcuts import render
from django.http import JsonResponse, HttpResponse
from usuarios.models import Usuario
from .models import Post, ComentarioPost, Like, Notificaciones

def home(request):
    user_followed = Usuario.objects.filter(followers=request.user)
    posts = Post.objects.filter(usuario__in=user_followed)
    results = []
    for pub in posts:
        results.append(pub)
        if Like.objects.filter(post=pub, user=request.user).exists():
            pub.is_liked = True
    contexto = {
        'posts': results
    }
    return render(request, 'fotos/feed.html', contexto)

def post_comments(request, id):
    post = Post.objects.get(id=id)
    contexto = {'post': post}
    return render(request, 'fotos/comentarios.html', contexto)

def post_form(request):
    return render(request, 'fotos/post_form.html')

def subir_foto(request):
    salida = {}
    if request.method == 'POST' and request.is_ajax():
        imagen_ = request.FILES.get('post')
        pie_foto = request.POST.get('pie')
        user = Usuario.objects.get(id=request.user.id)
        fecha_ = timezone.now()

        if imagen_ and pie_foto:
            post = Post.objects.create(
                imagen=imagen_,
                fecha=fecha_,
                pie=pie_foto,
                usuario=user,
            )
            post.save()
            salida = {'success': True, 'msj': 'Post subido correctamente'}
        else:
            salida = {'error': True, 'msj': 'Por favor llena todos los campos'}
    return HttpResponse(JsonResponse(salida))

def pub_detalles(request, id):
    is_liked = False
    is_saved = False
    pub = Post.objects.get(id=id)
    num_likes = Like.objects.filter(post=pub).count()
    if Like.objects.filter(post=pub, user=request.user).exists():
        is_liked = True
    if pub.guardar.filter(id=request.user.id).exists():
        is_saved = True
    comentarios = ComentarioPost.objects.filter(post_id=pub.id)
    contexto = {
        'foto': pub,
        'comentarios': comentarios,
        'is_liked': is_liked,
        'is_saved': is_saved,
        'num_likes': num_likes
    }
    return render(request, 'fotos/pub_detalles.html', contexto)

def likear(request, id):
    salida = {}
    foto = Post.objects.get(id=id)
    second_user = foto.usuario
    current_user = request.user
    if request.method == 'POST' and request.is_ajax():
        if Like.objects.filter(post=foto, user=current_user).exists():
            like_object = Like.objects.filter(post=foto, user=current_user)
            like_object.delete()
            salida = {'deleted': True}
        else:
            date = timezone.now()
            like_object = Like.objects.create(
                post=foto,
                user=current_user,
                fecha=date
            )
            like_object.save()
            texto_ = 'le ha dado like tu foto'
            ntc = Notificaciones.objects.create(
                post=foto,
                f_user=current_user,
                fecha=date,
                s_user=second_user,
                texto = texto_
            )
            ntc.save()
            salida = {'liked': True}
    return HttpResponse(JsonResponse(salida))

def guardar_post(request, id):
    salida = {}
    foto = Post.objects.get(id=id)
    current_user = request.user
    if request.method == 'POST' and request.is_ajax():
        if foto.guardar.filter(id=current_user.id).exists():
            foto.guardar.remove(current_user)
            salida = {'removed': True}
        else:
            foto.guardar.add(current_user)
            salida = {'saved': True}
    return HttpResponse(JsonResponse(salida))

def comentar(request, id):
    salida = {}
    if request.method == 'POST' and request.is_ajax():
        pub = Post.objects.get(id=id)
        second_user = pub.usuario
        comentario = request.POST.get('comentario')
        date = timezone.now()
        if comentario:
            nuevo_comentario = ComentarioPost.objects.create(
                post=pub,
                fecha=date,
                user=request.user,
                texto=comentario
            )
            nuevo_comentario.save()
            texto_ = 'ha comentado tu foto'
            ntc = Notificaciones.objects.create(
                post=pub,
                f_user=request.user,
                fecha=date,
                s_user=second_user,
                texto=texto_
            )
            ntc.save()
            comentario_ajax = []
            comentario_info = {}
            name_ = request.user.username
            comentario_info['texto'] = nuevo_comentario.texto
            comentario_info['fecha'] = nuevo_comentario.fecha
            comentario_info['user'] = name_
            comentario_ajax.append(comentario_info)
            salida = {'success': True, 'info': comentario_ajax}
        else:
            salida = {'error': True}
    return HttpResponse(JsonResponse(salida))

def get_likes(request, id):
    pub = Post.objects.get(id=id)
    likes = Like.objects.filter(post=pub)
    contexto = {'likes': likes}
    return render(request, 'fotos/modal.html', contexto)

def get_saved(request):
    posts = Post.objects.filter(guardar=request.user)
    context = {'posts': posts}
    return render(request, 'fotos/guardados.html', context)

def busqueda(request):
    return render(request, 'fotos/buscador.html')

def notificaciones(request):
    nts = Notificaciones.objects.filter(s_user=request.user)
    contexto = {'notificaciones': nts}
    return render(request, 'fotos/notificaciones.html', contexto)

templates/fotos/buscador.html
{% extends 'base.html' %}
{% block header %}
<div class="header_re">
    <div class="links_re">
        <a href="{% url 'fotos:home' %}"><i class="fas fa-home"></i></a>
        <a href="{% url 'fotos:buscar' %}"><i class="fas fa-search"></i></a>
        <a href=""><i class="fas fa-bell"></i></a>
        <button data-toggle="modal" data-target="#modal_actions" id="actions" class="btn-3"><i class="fas fa-sort-down"></i></button>
        {% if request.user.is_authenticated %}
            {% if request.user.foto_perfil %}
                <a href="{% url 'usuario:user_home' %}">
                    <img class="circle3" src={% if request.user.foto_perfil %}'{{ request.user.foto_perfil.url }}'{% endif %} alt="">
                </a>
            {% else %}
                <a href="{% url 'usuario:user_home' %}"><i class="fas fa-user"></i></a>
            {% endif %}
        {% endif %}
    </div>
</div>
{% endblock %}
{% block content %}

<div class="busquedas">
    <form id="buscar">
        <input class="s_input" type="text" placeholder="Buscar usuarios" id="buscar_input" name="usuario">
    </form>
    <div class="results"></div>
</div>
{% endblock %}

{% block footer %}
{% endblock %}

templates/fotos/comentarios.html
{% extends 'base.html' %}

{% block content %}
<div class="re" id="pub_comment">
    <div class="caja_comments" >
        <div class="post_info_re_comment">
            <p class="mini">{{ post.fecha }}</p>
            <p><strong>{{ post.usuario.username }}</strong>. {{ post.pie }}</p>
        </div>
            <div class="new_comment"></div>
        {% if post.comments %}
            {% for comentario in post.comments %}
                <div class="comentario_">
                    <p class="mini">{{ comentario.fecha }}</p>
                    {% if comentario.user.username == request.user.username %}
                        <a href="{% url 'usuario:user_home' %}">
                            <strong>{{ request.user.username }}</strong>
                        </a>
                    {% else %}
                        <a href="{% url 'usuario:user_profile' comentario.user.id %}">
                            <strong>{{ comentario.user.username }}</strong>
                        </a>
                    {% endif %}
                    <p>{{ comentario.texto }}</p>
                </div>
            {% endfor %}
        {% endif %}
    </div>
    <div class="comentar">
        <form id="comentar_form">
            {% csrf_token %}
            <input class="input_pub" type="text" name="comentario" placeholder="Comentar...">
            <button value="{{ post.id }}" id="comentar" class="btn-full2 cmt">Subir</button>
        </form>
    </div>
</div>


{% endblock %}

{% block footer %}
{% endblock %}

templates/fotos/feed.html
{% extends 'base.html' %}

{% block content %}
<div class="feed">
    {% for post in posts %}
        <div class="post_details">
            <div class="user_info_re">
                <div class="user_re">
                    <a class="link_user" href="{% url 'usuario:user_profile' post.usuario.id %}">
                        {% if post.usuario.foto_perfil %}
                            <img class="circle3" src={% if post.usuario.foto_perfil %}'{{ post.usuario.foto_perfil.url }}'{% endif %} alt="">
                            {{ post.usuario.username }}
                        {% else %}
                            <i class="fas fa-user"></i>
                            {{ post.usuario.username }}
                        {% endif %}
                    </a>
                </div>   
            </div>
            <img src={% if post.imagen %}'{{ post.imagen.url }}'{% endif %} alt="">
            <div class="comments" id="pub_comment">
                <div class="user">
                    <a class="link_user" href="{% url 'usuario:user_profile' post.usuario.id %}">
                        {% if post.usuario.foto_perfil %}
                            <img class="circle3" src={% if post.usuario.foto_perfil %}'{{ post.usuario.foto_perfil.url }}'{% endif %} alt="">
                            {{ post.usuario.username }}
                        {% else %}
                            <i class="fas fa-user"></i>
                            {{ post.usuario.username }}
                        {% endif %}
                    </a>
                </div>
                <div class="details">
                    <p class="mini">{{ post.fecha }}</p>
                    <p><strong>{{ post.usuario.username }}</strong>. {{ post.pie }}</p>
                    <a href="{% url 'fotos:comentarios_re' post.id %}" class="btn-3 ver_cmm">Ver comentarios</a>
                </div>
                <div class="caja_comments">
                    <p class="mini">{{ post.fecha }}</p>
                    <p><strong>{{ post.usuario.username }}</strong>. {{ post.pie }}</p>
                    <div class="new_comment"></div>
                    {% if post.comments %}
                        {% for comentario in post.comments %}
                            <div class="comentario_">
                                <p class="mini">{{ comentario.fecha }}</p>
                                {% if comentario.user.username == request.user.username %}
                                    <a href="{% url 'usuario:user_home' %}">
                                        <strong>{{ request.user.username }}</strong>
                                    </a>
                                {% else %}
                                    <a href="{% url 'usuario:user_profile' comentario.user.id %}">
                                        <strong>{{ comentario.user.username }}</strong>
                                    </a>
                                {% endif %}
                                <p>{{ comentario.texto }}</p>
                            </div>
                        {% endfor %}
                    {% endif %}
                </div>
                <div class="likes">
                    <a data-url="{% url 'fotos:like' post.id %}" class="open_modal">{{ post.num_likes }} <i class="fas fa-heart"></i></a>
                    <div class="forms">
                        <form class="pub_form" id="like">
                            {% csrf_token %}
                            {% if post.is_liked %}
                                <button value="{{ post.id }}" class="btn-3 like liked" id="liked"><i class="fas fa-heart"></i></button>
                                <button value="{{ post.id }}" style="display: none;" class="btn-3 like deleted" id="unliked"><i class="far fa-heart"></i></button>
                            {% else %}
                                <button value="{{ post.id }}" class="btn-3 like deleted" id="unliked"><i class="far fa-heart"></i></button>
                                <button value="{{ post.id }}" style="display: none;" class="btn-3 like liked" id="liked"><i class="fas fa-heart"></i></button>
                            {% endif %}
                        </form>
                        <form class="pub_form" id="save">
                            {% csrf_token %}
                            {% if request.user in post.guardar.all %}
                                <button value="{{ post.id }}" class="btn-3 guardar saved" id="saved"><i class="fas fa-bookmark"></i></button>
                                <button value="{{ post.id }}" style="display: none" class="btn-3 guardar removed" id="removed"><i class="far fa-bookmark"></i></button>
                            {% else %}
                                <button value="{{ post.id }}" class="btn-3 guardar removed" id="removed"><i class="far fa-bookmark"></i></button>
                                <button value="{{ post.id }}" style="display: none;" class="btn-3 guardar saved" id="saved"><i class="fas fa-bookmark"></i></button>
                            {% endif %}
                        </form>
                    </div>
                </div>
                <div class="comentar">
                    <form id="comentar_form">
                        {% csrf_token %}
                        <input class="input_pub" type="text" name="comentario" placeholder="Comentar...">
                        <button value="{{ post.id }}" id="comentar" class="btn-full2 cmt"><i class="fas fa-angle-right"></i></button>
                    </form>
                </div>
            </div>
            <div class="post_info">
                <p><strong>{{ post.usuario.username }}</strong>. {{ post.pie }}</p>
                <a href="{% url 'fotos:comentarios_re' post.id %}" class="btn-3 ver_cmm">Ver comentarios</a>
                <a data-url="{% url 'fotos:like' post.id %}" class="open_modal">{{ post.num_likes }} <i class="fas fa-heart"></i></a>
                <div class="forms_re">
                    <form class="pub_form" id="like">
                        {% csrf_token %}
                        {% if post.is_liked %}
                            <button value="{{ post.id }}" class="btn-3 like liked" id="liked"><i class="fas fa-heart"></i></button>
                            <button value="{{ post.id }}" style="display: none;" class="btn-3 like deleted" id="unliked"><i class="far fa-heart"></i></button>
                        {% else %}
                            <button value="{{ post.id }}" class="btn-3 like deleted" id="unliked"><i class="far fa-heart"></i></button>
                            <button value="{{ post.id }}" style="display: none;" class="btn-3 like liked" id="liked"><i class="fas fa-heart"></i></button>
                        {% endif %}
                    </form>
                    <form class="pub_form" id="save">
                        {% csrf_token %}
                        {% if request.user in post.guardar.all %}
                            <button value="{{ post.id }}" class="btn-3 guardar saved" id="saved"><i class="fas fa-bookmark"></i></button>
                            <button value="{{ post.id }}" style="display: none" class="btn-3 guardar removed" id="removed"><i class="far fa-bookmark"></i></button>
                        {% else %}
                            <button value="{{ post.id }}" class="btn-3 guardar removed" id="removed"><i class="far fa-bookmark"></i></button>
                            <button value="{{ post.id }}" style="display: none;" class="btn-3 guardar saved" id="saved"><i class="fas fa-bookmark"></i></button>
                        {% endif %}
                    </form>
                </div>
                
            </div>
        </div>   
    {% endfor %}
</div>
<div class="modal-div"></div>
{% endblock %}

templates/fotos/guardados.html
{% extends 'base.html' %}

{% block content %}

<div class="publicaciones">
    <h2>Elementos guardados</h2>
    {% if posts %}
        {% for foto in posts %}
            <div class="listado">
                <a href="{% url 'fotos:pub_detalles' foto.id %}">
                    <img src={% if foto.imagen %}'{{ foto.imagen.url }}'{% endif %} alt="">
                </a>
            </div>
        {% endfor %}
    {% else %}
    <div style="padding:50px 10px 50px 10px;">
        <h1>No hay publicaciones por el momento</h1>
    </div>
    {% endif %}
    <div class="explorar_mas">
        <a class="btn-3" href="{% url 'fotos:home' %}">Explorar mas publicaciones</a>
    </div>
</div>

{% endblock %}

templates/fotos/modal.html
<div class="modal fade" id="modal_likes" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content" id="modal">
            <div class="modal-header text-center">
                <h4 class="modal-title w-100" id="modaltit">Likes</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body mx-3" id="control">
                {% if likes %}
                    {% for like in likes %}
                        {% if like.user == request.user %}
                            {% if like.user.foto_perfil %}
                                <div class="md-form mb-2 d-flex justify-content-center">
                                    <a class="link_user" href="{% url 'usuario:user_home' %}">
                                        <img class="circle3" src={% if like.user.foto_perfil %}'{{ like.user.foto_perfil.url }}'{% endif %} alt="">
                                        {{ like.user.username }}
                                    </a>
                                </div>
                            {% else %}
                                <div class="md-form mb-2 d-flex justify-content-center">
                                    <a class="link_user" href="{% url 'usuario:user_home' %}">
                                        <i class="fas fa-user"></i>
                                        {{ like.user.username }}
                                    </a>
                                </div>
                            {% endif %}
                        {% else %}
                            {% if like.user.foto_perfil %}
                                <div class="md-form mb-2 d-flex justify-content-center">
                                    <a class="link_user" href="{% url 'usuario:user_profile' like.user.id %}">
                                        <img class="circle3" src={% if like.user.foto_perfil %}'{{ like.user.foto_perfil.url }}'{% endif %} alt="">
                                        {{ like.user.username }}
                                    </a>
                                </div>
                            {% else %}
                                <div class="md-form mb-2 d-flex justify-content-center">
                                    <a class="link_user" href="{% url 'usuario:user_profile' like.user.id %}">
                                        <i class="fas fa-user"></i>
                                        {{ like.user.username }}
                                    </a>
                                </div>
                            {% endif %}
                        {% endif %}
                    {% endfor %}
                {% endif %}
            </div>
        </div>
    </div>
</div>

templates/fotos/notificaciones.html
{% extends 'base.html' %}

{% block content %}

<div class="ntc">
    {% if notificaciones %}
        {% for ntc in notificaciones %}
        {% if ntc.post_id %}
            <div class="notificacion">
                <p>{{ ntc.fecha }}</p>
                <a href="{% url 'fotos:pub_detalles' ntc.post_id %}">
                    <p><strong>{{ ntc.f_user }}</strong> {{ ntc.texto }}</p>
                </a>
            </div>
        {% else %}
            <div class="notificacion">
                <p>{{ ntc.fecha }}</p>
                <a href="{% url 'usuario:user_profile' ntc.f_user.id %}">
                    <p><strong>{{ ntc.f_user }}</strong> {{ ntc.texto }}</p>
                </a>
            </div>
        {% endif %}
        {% endfor %}
    {% else %}
    <div class="n_ntc">
        <h2>No hay notificaciones por el momento</h2>
    </div>
    {% endif %}
</div>

{% endblock %}

templates/fotos/pub_detalles.html
{% extends 'base.html' %}

{% block header %}
{% endblock %}

{% block content %}
<div class="pub_detalles">
    <div class="info_re">
        <div class="user_">
            {% if foto.usuario == request.user %}
                <a class="link_user" href="{% url 'usuario:user_home' %}">
                    {% if request.user.foto_perfil %}
                        <img class="circle3" src={% if request.user.foto_perfil %}'{{ request.user.foto_perfil.url }}'{% endif %} alt="">
                        {{ request.user.username }}
                    {% else %}
                        <i class="fas fa-user"></i>
                        {{ request.user.username }}
                    {% endif %}
                </a>
            {% else %}
            <a class="link_user" href="{% url 'usuario:user_profile' foto.usuario.id %}">
                {% if foto.usuario.foto_perfil %}
                    <img class="circle3" src={% if foto.usuario.foto_perfil %}'{{ foto.usuario.foto_perfil.url }}'{% endif %} alt="">
                    {{ foto.usuario.username }}
                {% else %}
                    <i class="fas fa-user"></i>
                    {{ foto.usuario.username }}
                {% endif %}
            </a>
            {% endif %}
        </div>
        <p><i class="fas fa-calendar"></i> {{ foto.fecha }}</p>
    </div>
    <div class="foto">
        <div class="img_info">
            <img src={% if foto.imagen %}'{{ foto.imagen.url }}'{% endif %} alt="">
        </div>
        <div class="likes_">
            <a data-url="{% url 'fotos:like' foto.id %}" class="open_modal">{{ num_likes }} <i class="fas fa-heart"></i></a>
        </div>
        <div class="forms_">
            <form class="pub_form" id="like">
                {% csrf_token %}
                {% if is_liked %}
                    <button value="{{ foto.id }}" class="btn-3 like liked" id="liked"><i class="fas fa-heart"></i></button>
                    <button value="{{ foto.id }}" style="display: none;" class="btn-3 like deleted" id="unliked"><i class="far fa-heart"></i></button>
                {% else %}
                    <button value="{{ foto.id }}" class="btn-3 like deleted" id="unliked"><i class="far fa-heart"></i></button>
                    <button value="{{ foto.id }}" style="display: none;" class="btn-3 like liked" id="liked"><i class="fas fa-heart"></i></button>
                {% endif %}
            </form>
            <form class="pub_form" id="save">
                {% csrf_token %}
                {% if is_saved %}
                    <button value="{{ foto.id }}" class="btn-3 guardar saved" id="saved"><i class="fas fa-bookmark"></i></button>
                    <button value="{{ foto.id }}" style="display: none" class="btn-3 guardar removed" id="removed"><i class="far fa-bookmark"></i></button>
                {% else %}
                    <button value="{{ foto.id }}" class="btn-3 guardar removed" id="removed"><i class="far fa-bookmark"></i></button>
                    <button value="{{ foto.id }}" style="display: none;" class="btn-3 guardar saved" id="saved"><i class="fas fa-bookmark"></i></button>
                {% endif %}
            </form>
        </div>
    </div>
    <div class="comentarios" id="pub_comment">
        <div class="info">
            <div class="user_">
                {% if foto.usuario == request.user %}
                    <a class="link_user" href="{% url 'usuario:user_home' %}">
                        {% if request.user.foto_perfil %}
                            <img class="circle3" src={% if request.user.foto_perfil %}'{{ request.user.foto_perfil.url }}'{% endif %} alt="">
                            {{ request.user.username }}
                        {% else %}
                            <i class="fas fa-user"></i>
                            {{ request.user.username }}
                        {% endif %}
                    </a>
                {% else %}
                <a class="link_user" href="{% url 'usuario:user_profile' foto.usuario.id %}">
                    {% if foto.usuario.foto_perfil %}
                        <img class="circle3" src={% if foto.usuario.foto_perfil %}'{{ foto.usuario.foto_perfil.url }}'{% endif %} alt="">
                        {{ foto.usuario.username }}
                    {% else %}
                        <i class="fas fa-user"></i>
                        {{ foto.usuario.username }}
                    {% endif %}
                </a>
                {% endif %}
            </div>
            <p><i class="fas fa-calendar"></i> <strong>{{ foto.fecha }}</strong></p>
        </div>
        <div class="comentarios_users">
            <p><strong>{{ foto.usuario.username }}</strong>. {{ foto.pie }}</p>
            <div class="new_comment"></div>
            {% if comentarios %}
                {% for comentario in comentarios %}
                    <div class="comentario_">
                        <p class="mini">{{ comentario.fecha }}</p>
                        {% if comentario.user.username == request.user.username %}
                            <a href="{% url 'usuario:user_home' %}">
                                <strong>{{ request.user.username }}</strong>
                            </a>
                        {% else %}
                            <a href="{% url 'usuario:user_profile' comentario.user.id %}">
                                <strong>{{ comentario.user.username }}</strong>
                            </a>
                        {% endif %}
                        <p>{{ comentario.texto }}</p>
                    </div>
                {% endfor %}
            {% endif %}
        </div>
        <div class="comentar2">
            <form id="comentar_form">
                {% csrf_token %}
                <input class="input_pub" type="text" name="comentario" placeholder="Comentar...">
                <button value="{{ foto.id }}" id="comentar" class="btn-full2 cmt">Subir</button>
            </form>
        </div>
    </div>
</div>
<div class="modal-div"></div>
{% endblock %}

{% block footer %}
{% endblock %}